### ISSUE TITLE
Get RiggingToolbox working in Fabric Engine 2.0 and Canvas

### ISSUE THREAD

**Issue by BigRoy** [fabric-engine/RiggingToolbox#8]
Outside of seeing some videos showing off the RiggingToolbox it has been hard to find just the right documentation to get it working, especially figuring out whether anyone got this working with Fabric Engine 2.0 (pablo).

The `pablo` branch `README` states that it is only updated to be compatible with its DeltaMush implementation, yet it doesn't show how to get it to work. Whenever I try to load up the toolkit it will raise errors like:

```
[FABRIC:MT] [RiggingToolbox] GeometryStack/Manipulation/Weightmap2.kl:78:9: error: no extension or type named 'SpliceInterfaces'
[FABRIC:MT] [RiggingToolbox] Error encountered while loading extension; extension disabled
[FABRIC:MT] [RiggingToolbox] Error description: KL compile failed: no extension or type named 'SpliceInterfaces'
```

- Are there any plans to update the RiggingToolbox to be fully compatible with 2.0+? And will it support a Canvas based-workflow?

**Comment by BigRoy** [comment]
Ah, should've just pushed through that error. Removing the require statement allowed me to load up the RiggingToolbox. Now just need to investigate some more on using it.

**Comment by BigRoy** [comment]
Ok, so I've gotten a bit further. I had to add some code snippet into the Alembic Generators as I kept getting errors that an Xfo was being sampled from a PolyMesh. Basically I changed the computeGlobalXfo on the mesh to:

```
    // TODO: This is a temporary hack because FE 2.0 was giving errors that it was reading Xfo
    //       from PolyMesh instead of Xfo. Not sure if this is the correct 'fix'
    // Get the transform from the PolygonMesh (parent transform)
    String hierarchy[] = polymeshPaths[i].split("/");
    hierarchy.pop(); // Remove the shape item
    String transform = "/".join(hierarchy);

    Xfo globalXfo = this.computeGlobalXfo(this.time, archive, transform);
```

That seems to be working out perfectly. I've finally been able to draw the tubeCharacter example file in Canvas using a GeometryStack!

The next issue is adding in Modifiers in the chain. 

Apparently `cachePoint` attribute in `GeometryStack.evaluate` is `null`. 

```
[FABRIC:MT] Error: method CachePoint.update!(io GeometrySet, GeometryOperator) called on null interface
```

This only happens for Modifiers, not for the generators.
It's within this area of the code:

```
      CachePoint cachePoint = this.cachePoints[i];
      if(cachePoint == null){
        Generator generator = op;
        if(generator)
          cachePoint = GeometryCache();
        else
          cachePoint = GeometryAttributeCache(op);
        this.cachePoints[i] = cachePoint;
      }
```

It seems that the result of `GeometryAttributeCache(op)` returns `null` even though the variable *op* is not null. 

Any particular reason why it might act this way?

**Comment by BigRoy** [comment]
> Any particular reason why it might act this way?

Actually I figured this out because I saw this comment in the code elsewhere:  `// No implicit casting in KL from objects to interfaces.`

Added this in the code:

```
          // #8 Bugfix: Explicit type cast for interfaces in KL, otherwise GeometryAttributeCache returns null
          BaseModifier mod = op; 
          cachePoint = GeometryAttributeCache(mod);
```

Now no more errors in that area. Actually... I now have the tubeCharacter examples working in Maya with the old splice nodes in Fabric Engine 2.0. That's a start. 

Actually I have a Canvas graph with some nodes laid out working without errors as well... just need to connect the deformers to it I suppose.

**Comment by BigRoy** [comment]
I didn't reference it in the commit, but the [issue with computeGlobalXfo mentioned above](https://github.com/fabric-engine/RiggingToolbox/issues/8#issuecomment-150939050) was fixed in [this commit](https://github.com/BigRoy/RiggingToolbox/commit/a6032438df351088c8da546b594ae3ee8d3c73aa).

Not sure if I should be working in my forked *pablo* branch or my own separate branch to get a good pull request going. But since these are all fixes aimed towards 2.0 (Pablo) I hope all is good like this.

Should I setup a Pull Request? The Splice examples of the tubeCharacter are working in Maya with the Splice nodes.

Next step could be to run `KL2DFG` add the dynamically built presets to the repository and add an example fully functional graph working in Canvas.

**Comment by BigRoy** [comment]
Actually... let me just drop [this example video here](https://twitter.com/Royn3D/status/658385300062904320) here.

Basically dropped the code from the operators of one of the example files in a Canvas graph as custom functions. (No `KL2DFG` done yet) 

Works great. And seemed like similar speeds as the splice node version, or at least it didn't seem any slower.

**Comment by phtaylor** [comment]
Hi Roy, would you be able to push your changes on a branch that I can take a look at?
I've finally got some time to take a look at this stuff for you.

**Comment by phtaylor** [comment]
BTW: it looks great in the video! You have gotten a long way.

**Comment by BigRoy** [comment]
Of course, will do so in about 10-15 minutes.

So I basically check it out in a new branch in my forked repo and link it here? Or set up a separate PR from that branch into this branch? What's the workflow there?

**Comment by phtaylor** [comment]
I think you need to use a 'pull request', to bring changes upstream from your fork.

**Comment by BigRoy** [comment]
Actually, a pull request is open, see https://github.com/fabric-engine/RiggingToolbox/issues/9

Yet it is from the same named branch because i was only working on the *pablo* fixes. Didn't change anything other than that really.

**Comment by phtaylor** [comment]
ok, great. Thanks. I'll take  a look

**Comment by BigRoy** [comment]
With #9 issue merged there is a working [Pablo branch](https://github.com/fabric-engine/RiggingToolbox/tree/pablo) running in Canvas and Fabric Engine 2.0. 

The core issue here still stands and is that we need presets and examples to show within Canvas how the power of RiggingToolbox can leveraged inside a node graph.

So to define a goal here:

## Goal

Set up a Canvas workflow with presets and some examples to develop a "common language" and "understanding" of how these graphs procedurally work with the Generators, Modifiers and things like the GeometryStack.

**Comment by BigRoy** [comment]
With this issue and comments now more focused on getting the Pablo branch functioning I think it's ready to be closed.
